version: "3"

services:
  app:
    container_name: timelite
    build: .
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    command: npx next start --port ${PORT}
    restart: unless-stopped
